### ISSUE TITLE
Unitframes are not moveable

### ISSUE THREAD

**Issue by daneras** [renstrom/NeavUI#174]
Hi,

i have updateded your last upload here on the Betarealm. I saw that you have killed the option to unlock the UF, TF and FF so i tryed to set the position in your config.lua file.
No impact on UI reload.

Can you say me how i can move the UF's in your actual build with ouf_Neav?

Thx man.

**Comment by renstrom** [comment]
Well, it's still there. We just removed the custom drop down since it was causing taint issues ("action blocked by bla bla..."). But you can move the frames in the same way you move the pet-/stancebar, just press alt-shift and drag with your mouse outside of combat.

And then you can use the `/neavreset` slash command to reset positions.

**Comment by daneras** [comment]
Ah wow, that's a very nice improvement. Many thx for the tip. Have a nice day.

**Comment by renstrom** [comment]
Well the cred should go to @Grimsbain, he's the one who did all the work :)

**Comment by daneras** [comment]
The thx to @Grimsbain for your great work, and all others from this project too :)
