### ISSUE TITLE
ouf folder

### ISSUE THREAD

**Issue by thorin39** [renstrom/NeavUI#205]
ouf folder is empty in latest release

**Comment by renstrom** [comment]
Do you mean here on GitHub or on WoWInterface?

**Comment by thorin39** [comment]
here https://codeload.github.com/renstrom/NeavUI/zip/7.0.3

**Comment by renstrom** [comment]
Unfortunately I can't do much about that since those are automatically generated by GitHub, and they never include submodules (sigh!). That means both `oUF` and `nPlates` will be empty.

*However*, I manually added a proper package to the release as you can see from the picture below.

![screen shot 2016-08-26 at 09 24 36](https://cloud.githubusercontent.com/assets/177685/17997471/11f98912-6b6f-11e6-9ce9-37952791661e.png)
